import json
from pathlib import Path

import pytest

from backend.link import SerialLink
from backend.device import DeviceModel, ProtoMismatch, DeviceError
from tests.fake_serial import FakeSerial

# Golden fixture, not a hand-typed literal: generated by
# firmware/test/test_dispatch/test_dispatch.cpp
# (test_schema_golden_fixture_matches_firmware) from a real
# Dispatcher::handle("schema") call. Loading it here -- instead of
# hand-typing a Python SCHEMA dict -- is what makes a firmware schema change
# (e.g. a bumped `max`) show up as a Python test failure instead of silently
# validating against a stale bound. Regenerate by running
# `pio test -e native` in firmware/ after any core/params.cpp change.
_GOLDEN_SCHEMA_PATH = (
    Path(__file__).resolve().parents[2] / "firmware" / "test" / "golden" / "schema.json"
)
_GOLDEN = json.loads(_GOLDEN_SCHEMA_PATH.read_text())
SCHEMA = _GOLDEN["params"]
# The telemetry descriptor comes from the same fixture, so the field set the
# fake device advertises is the real firmware's -- adding a sensor module to a
# board cannot leave these tests passing against a stale field list.
TLM_SCHEMA = _GOLDEN["tlm"]
VALUES = {"rx.protocol": "elrs", "rx.deadband_us": 2,
          "device.name": "betacrawler", "tlm.rate": 10}


def device_responder(proto=1, caps=("dfu",), revert_src="flash",
                     knows_revert=True):
    def responder(req, emit):
        op = req["op"]
        rid = req["id"]
        if op == "hello":
            emit({"id": rid, "ok": True, "fw": "betacrawler 1.0.0",
                  "proto": proto, "board": "blackpill_f411ce",
                  "name": "betacrawler", "ver": "1.0.0",
                  "built": "Jul 26 2026 14:03:11",
                  "mods": ["device", "system", "button", "led"],
                  "caps": list(caps)})
        elif op == "schema":
            emit({"id": rid, "ok": True, "params": SCHEMA, "tlm": TLM_SCHEMA})
        elif op == "getall":
            emit({"id": rid, "ok": True, "vals": dict(VALUES)})
        elif op == "get":
            key = req["key"]
            if key in VALUES:
                emit({"id": rid, "ok": True, "key": key, "val": VALUES[key]})
            else:
                emit({"id": rid, "ok": False, "err": "nokey"})
        elif op == "set":
            emit({"id": rid, "ok": True})
        elif op in ("save", "defaults"):
            emit({"id": rid, "ok": True})
        elif op == "revert" and knows_revert:
            # knows_revert=False falls through to the `badop` branch below,
            # which is exactly what firmware predating the op answers.
            # Mirrors the firmware: never an error, but says which source it
            # used so the host can tell "back to saved" from "fell back".
            # revert_src=None simulates a firmware that omits `src` entirely
            # (protocol skew), to exercise DeviceModel's fail-safe default.
            resp = {"id": rid, "ok": True}
            if revert_src is not None:
                resp["src"] = revert_src
            emit(resp)
        elif op == "dfu":
            # Mirrors the firmware: it answers BEFORE resetting, so an `ok`
            # here means "request accepted", not "already rebooted".
            emit({"id": rid, "ok": True} if "dfu" in caps
                 else {"id": rid, "ok": False, "err": "nodfu"})
        elif op == "wifiscan":
            # Mirrors the firmware: "busy" isn't modeled here (no test needs
            # a mid-scan request), only the capability gate.
            emit({"id": rid, "ok": True} if "wifiscan" in caps
                 else {"id": rid, "ok": False, "err": "nowifi"})
        else:
            emit({"id": rid, "ok": False, "err": "badop"})
    return responder


def make_device(proto=1, caps=("dfu",)):
    fake = FakeSerial(responder=device_responder(proto, caps=caps))
    return DeviceModel(SerialLink(open_port=lambda p: fake)), fake


def test_connect_caches_schema_and_values():
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        assert dev.status()["state"] == "connected"
        assert dev.status()["proto"] == 1
        assert len(dev.schema()["params"]) == 27
        assert len(dev.schema()["tlm"]) == 37
        assert dev.values()["rx.deadband_us"] == 2
    finally:
        dev.disconnect()


def test_connect_caches_build_identity_and_module_list():
    """The structured hello fields must survive into status(), which is what
    the UI reads -- they are additive, so a regression here is silent."""
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        st = dev.status()
        assert st["fw"] == "betacrawler 1.0.0"     # display string, unchanged contract
        assert st["name"] == "betacrawler"
        assert st["ver"] == "1.0.0"
        assert st["built"].startswith("Jul 26 2026")
        assert st["mods"] == ["device", "system", "button", "led"]
    finally:
        dev.disconnect()


def test_missing_optional_hello_fields_do_not_break_connect():
    """Firmware predating the module refactor omits name/ver/built/mods.
    Connecting must still succeed rather than KeyError on the handshake."""
    def old_firmware(req, emit):
        rid = req["id"]
        if req["op"] == "hello":
            emit({"id": rid, "ok": True, "fw": "betacrawler 0.1.0",
                  "proto": 1, "board": "blackpill_f411ce"})
        elif req["op"] == "schema":
            emit({"id": rid, "ok": True, "params": SCHEMA})
        elif req["op"] == "getall":
            emit({"id": rid, "ok": True, "vals": dict(VALUES)})
        else:
            emit({"id": rid, "ok": True})

    fake = FakeSerial(responder=old_firmware)
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        assert dev.status()["ver"] is None
        assert dev.status()["mods"] == []
        assert dev.schema()["tlm"] == []      # no descriptor -> no telemetry cards
    finally:
        dev.disconnect()


def test_status_reports_the_connected_port():
    fake = FakeSerial(responder=device_responder())
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/ttyFAKE0")
    assert dev.status()["port"] == "/dev/ttyFAKE0"
    dev.disconnect()


def test_status_port_is_none_before_any_connection():
    dev = DeviceModel(SerialLink(open_port=lambda p: FakeSerial(responder=device_responder())))
    assert dev.status()["port"] is None


def test_status_port_survives_disconnect_like_board_and_fw_do():
    """Matches the existing behavior of board/fw/caps: status() keeps
    reporting the last-known value after a disconnect, not None -- the
    Firmware page's "not connected (last seen: ...)" text relies on exactly
    this pattern for `board` already."""
    fake = FakeSerial(responder=device_responder())
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/ttyFAKE0")
    dev.disconnect()
    assert dev.status()["port"] == "/dev/ttyFAKE0"


def test_status_port_is_cleared_on_a_failed_connect():
    def boom(p):
        raise OSError("no such port")
    dev = DeviceModel(SerialLink(open_port=boom))
    with pytest.raises(DeviceError):
        dev.connect("/dev/ttyGHOST")
    assert dev.status()["port"] is None


def test_proto_mismatch_refuses_connection():
    dev, _ = make_device(proto=99)
    with pytest.raises(ProtoMismatch):
        dev.connect("/dev/fake")
    assert dev.status()["state"] == "disconnected"


def test_set_validates_against_cached_schema_before_sending():
    dev, fake = make_device()
    dev.connect("/dev/fake")
    try:
        before = len(fake.written)
        with pytest.raises(DeviceError) as exc:
            dev.set("rx.deadband_us", 999)         # max is 200
        assert exc.value.code == "range"
        assert len(fake.written) == before        # nothing hit the wire
    finally:
        dev.disconnect()


def test_set_rejects_unknown_enum_option():
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.set("rx.protocol", "purple")
        assert exc.value.code == "enum"
    finally:
        dev.disconnect()


def test_set_rejects_overlong_string():
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.set("device.name", "x" * 40)
        assert exc.value.code == "toolong"
    finally:
        dev.disconnect()


def test_set_unknown_key_rejected():
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.set("no.such.key", 1)
        assert exc.value.code == "nokey"
    finally:
        dev.disconnect()


def test_successful_set_updates_the_cache():
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        dev.set("rx.deadband_us", 15)
        assert dev.values()["rx.deadband_us"] == 15
    finally:
        dev.disconnect()


def test_set_accepts_exact_max_boundary():
    """Mirrors test_params.cpp's boundary-accept check (max is inclusive)."""
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        dev.set("rx.deadband_us", 200)
        assert dev.values()["rx.deadband_us"] == 200
    finally:
        dev.disconnect()


def test_set_accepts_exact_maxlen_boundary():
    """Mirrors test_params.cpp's boundary-accept check (maxlen is inclusive)."""
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        name = "x" * 31
        dev.set("device.name", name)
        assert dev.values()["device.name"] == name
    finally:
        dev.disconnect()


def test_handshake_timeout_raises_device_error():
    """Timeout during hello/schema/getall handshake wraps in DeviceError."""
    def silent_responder(req, emit):
        # Never reply — forces timeout
        pass

    fake = FakeSerial(responder=silent_responder)
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    with pytest.raises(DeviceError) as exc:
        dev.connect("/dev/fake")
    assert exc.value.code == "timeout"
    assert dev.status()["state"] == "disconnected"


def test_connect_port_open_failure_raises_device_error():
    """Port-open failure wraps in DeviceError."""
    def bad_open(port):
        raise IOError(f"Port {port} not found")

    dev = DeviceModel(SerialLink(open_port=bad_open))
    with pytest.raises(DeviceError) as exc:
        dev.connect("/dev/nonexistent")
    assert exc.value.code == "connect_failed"
    assert "Port /dev/nonexistent not found" in str(exc.value)
    assert dev.status()["state"] == "disconnected"


# --- DFU ---------------------------------------------------------------------

def _connected(caps=("dfu",)):
    fake = FakeSerial(responder=device_responder(caps=caps))
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    return dev


def test_caps_are_reported_in_status():
    dev = _connected()
    try:
        assert dev.status()["caps"] == ["dfu"]
    finally:
        dev.disconnect()


def test_caps_default_to_empty_for_firmware_that_predates_them():
    """`caps` was added after Project 1 shipped. Older firmware omits it, and
    must come through as "no capabilities" rather than a KeyError."""
    dev = _connected(caps=())
    try:
        assert dev.status()["caps"] == []
    finally:
        dev.disconnect()


def test_enter_dfu_drops_the_link():
    """The port vanishes a moment after the ack, so the link is closed here.

    Letting the reader thread discover the dead port instead would surface a
    spurious "connection lost" at the exact moment things worked correctly.
    """
    dev = _connected()
    try:
        dev.enter_dfu()
        assert dev.status()["state"] == "disconnected"
    finally:
        dev.disconnect()


def test_enter_dfu_on_firmware_without_dfu_support():
    dev = _connected(caps=())
    try:
        with pytest.raises(DeviceError) as exc:
            dev.enter_dfu()
        assert exc.value.code == "nodfu"
        assert "BOOT0" in str(exc.value)
        # Still connected: a refused request must not drop a working link.
        assert dev.status()["state"] == "connected"
    finally:
        dev.disconnect()


def test_enter_dfu_on_firmware_too_old_to_know_the_op():
    """Real firmware from before this feature answers `badop`.

    Verified against the actual board: a pre-DFU build returns badop, and
    surfacing that raw would put a protocol token in front of a user whose
    actual problem -- and fix -- is identical to FEATURE_DFU being off.
    """
    def old_firmware(req, emit):
        rid = req["id"]
        if req["op"] == "hello":
            emit({"id": rid, "ok": True, "fw": "betacrawler 1.0.0", "proto": 1,
                  "board": "blackpill_f411ce"})
        elif req["op"] == "schema":
            emit({"id": rid, "ok": True, "params": SCHEMA, "tlm": TLM_SCHEMA})
        elif req["op"] == "getall":
            emit({"id": rid, "ok": True, "vals": dict(VALUES)})
        else:
            emit({"id": rid, "ok": False, "err": "badop"})

    fake = FakeSerial(responder=old_firmware)
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.enter_dfu()
        assert exc.value.code == "nodfu"
        assert "BOOT0" in str(exc.value)
    finally:
        dev.disconnect()


# --- WiFi scan -----------------------------------------------------------------

def test_start_wifi_scan_sends_wifiscan_op():
    # caps includes both "dfu" and "wifiscan" deliberately: if start_wifi_scan
    # sent the wrong op string (e.g. "dfu" by copy-paste from enter_dfu), the
    # fake would still answer ok:true and a bare "must not raise" assertion
    # would miss it -- so this also pins down the literal op on the wire.
    dev, fake = make_device(caps=("dfu", "wifiscan"))
    dev.connect("/dev/fake")
    try:
        dev.start_wifi_scan()   # must not raise
        last_req = json.loads(fake.written[-1].decode())
        assert last_req["op"] == "wifiscan"
    finally:
        dev.disconnect()


def test_start_wifi_scan_raises_when_unsupported():
    dev, _ = make_device(caps=("dfu",))   # no "wifiscan"
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.start_wifi_scan()
        assert exc.value.code == "nowifi"
        assert "does not support scanning" in str(exc.value)
    finally:
        dev.disconnect()


def test_start_wifi_scan_on_firmware_too_old_to_know_the_op():
    """`badop` means the board predates the op entirely -- the same shape
    enter_dfu()'s `nodfu`/`badop` handling covers. Must map to the same
    friendly `nowifi` code/message as the `nowifi` case above, not leak the
    raw wire token to a caller that cannot do anything useful with it."""
    def old_firmware(req, emit):
        rid = req["id"]
        if req["op"] == "hello":
            emit({"id": rid, "ok": True, "fw": "betacrawler 1.0.0", "proto": 1,
                  "board": "blackpill_f411ce"})
        elif req["op"] == "schema":
            emit({"id": rid, "ok": True, "params": SCHEMA, "tlm": TLM_SCHEMA})
        elif req["op"] == "getall":
            emit({"id": rid, "ok": True, "vals": dict(VALUES)})
        else:
            emit({"id": rid, "ok": False, "err": "badop"})

    fake = FakeSerial(responder=old_firmware)
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.start_wifi_scan()
        assert exc.value.code == "nowifi"
        assert "does not support scanning" in str(exc.value)
    finally:
        dev.disconnect()


def test_revert_reports_the_source_and_refreshes_values():
    dev, _ = make_device()
    dev.connect("/dev/fake")
    try:
        dev.set("rx.deadband_us", 15)
        assert dev.revert() == "flash"
        assert dev.values() == VALUES        # re-read from the device, not assumed
    finally:
        dev.disconnect()


def test_revert_reports_the_defaults_fallback():
    fake = FakeSerial(responder=device_responder(revert_src="defaults"))
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        assert dev.revert() == "defaults"
    finally:
        dev.disconnect()


def test_revert_defaults_to_the_save_prompting_source_when_firmware_omits_src():
    """Protocol skew: firmware that answers `ok:true` with no `src` at all
    (older/future build we don't recognise) must not be read as "flash" --
    that would silently hide unsaved state. "defaults" is the fail-safe
    default: worst case a spurious save prompt, never lost data."""
    fake = FakeSerial(responder=device_responder(revert_src=None))
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        assert dev.revert() == "defaults"
    finally:
        dev.disconnect()


def test_revert_on_firmware_too_old_to_know_the_op_says_so():
    """`badop` means the board predates the op, not that a flash write failed.
    A bare "revert failed" would send someone hunting a hardware fault when the
    fix is to flash the image the app already ships."""
    fake = FakeSerial(responder=device_responder(knows_revert=False))
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.revert()
        assert exc.value.code == "badop"
        assert "too old" in str(exc.value)
        assert "Firmware page" in str(exc.value)
    finally:
        dev.disconnect()


def test_terminal_revert_on_old_firmware_gives_the_same_message():
    """The Terminal and the button must not drift apart on the one failure a
    user is likely to hit -- both go through _revert_error()."""
    fake = FakeSerial(responder=device_responder(knows_revert=False))
    dev = DeviceModel(SerialLink(open_port=lambda p: fake))
    dev.connect("/dev/fake")
    try:
        with pytest.raises(DeviceError) as exc:
            dev.terminal_revert()
        assert exc.value.code == "badop"
        assert "too old" in str(exc.value)
    finally:
        dev.disconnect()
