[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = stlink
debug_tool = stlink
build_flags =
    -DUSBCON
    -DUSBD_USE_CDC
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.4

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17 -I src
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
lib_compat_mode = off
test_build_src = yes
build_src_filter = +<core/*>
